---
output: github_document
---

# loadenv

The goal of loadenv is to set up a clean package environment.

## The Problem

Have you ever had questions about which packages are loaded from some place in your code via `library()`? Did you face masking problems from certain packages such as `stats::filter()` or `dplyr::filter()`? Would you want to write clean code, being sure about your packages loaded?

loadenv will solve those problems. loadenv will ...

-   Clean up your global environment and remove all object, symbols, and plots
-   Install missing packages from your `packages` list
-   Lint and tidy your code to ensure clean coding
-   Unload all packages currently loaded
-   Load packages from your `packages` list
-   Analyse your code for used functions
-   Analyse your code for used packages
-   Find which loaded packages are not used
-   give you a report about packages, which can be removed from the `packages` list
-   Clean up your global environment and remove all object, symbols, and plots

## Installation

You can install the development version of loadenv like so:

``` r
#install.packages("devtools")
if ("loadenv" %in% rownames(installed.packages()) == FALSE) {
  devtools::install_github("fdutine79/loadenv")
}
```

## Load your environment

Place your installation of loadenv first thing in your code.

-   Update the package list `packages` with your own.
-   Specify GitHub hosted packages with full host name.
-   Specify CRAN packages by their name on CRAN.

Run `load_environment(packages)`.

``` r
packages <- c(
  "fdutine79/autotest",
  "dplyr"
)
loadenv::load_environment(packages)
```

The default setting is adjusted for fast run (parameter `fast = TRUE`). Linting and cleansing suggestions will therefore not be executed but packages will be loaded (`library()`). Add/change the logical argument to `fast = FALSE` to install missing packages, execute linting, identify superfluous packages and to get notified, which packages can be removed from the environment:

`loadenv::load_environment(packages, fast = FALSE)`
